version: '3'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
    - 27017:27017
    volumes:
    - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'desafio'
    networks:
      - app-network
  rabbit:
    image: rabbitmq
    container_name: rabbit
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      APP_PORT: 80
    ports:
    - 80:80
    depends_on:
      - mongodb
      - rabbit
    networks:
      - app-network
networks:
  app-network:
    driver: bridge