server:
  port: ${APP_PORT:8080}
  error:
    include-message: always

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: desafio
      username: admin
      password: password
      authentication-database: admin
  rabbitmq:
    username: rabbit
    password: rabbit
    port: 5672
    host: rabbit

feign:
  autoconfiguration:
    jackson:
      enabled: true
user:
  url: "http://user-info.herokuapp.com"

rabbit:
  exchange: sicredi
  queues:
    voto: voto
    resultado: resultado
  routingkeys:
    voto: votacao
    resultado: resultado