server:
  port: 8088

spring:
  data:
    mongodb:
#      uri: mongodb+srv://gsantosc18:bancoMongo%40123@cluster0.vnkd4.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      host: localhost
      port: 27017
      database: desafio
      username: admin
      password: password
      authentication-database: admin

feign:
  autoconfiguration:
    jackson:
      enabled: true
user:
  url: "http://user-info.herokuapp.com"